# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f09b5f75e7cdcddef520defbd92f2065fc57aa2ca1e2042b1c2f9e57f3c8673fc546bbb29b7629a0c8ae9341a5a766ce7ae0f02861e91426d0993af69b039d7

test:
  secret_key_base: 717c8dd7e54c9721a2fbdabce67239d751e212e7d5b1a3cee39a63abb97bc71737609038c63c72adbedd4ac19fa16a882672d122a0d734c61372e5403b1aedd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
